version: '3'
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: react_board
    ports:
      - "3306:3306"
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      timeout: 2s
      retries: 100

  backend:
    image: kimmingyu0/backend:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    image: kimmingyu0/frontend:0.0.1-SNAPSHOT
    ports:
      - "3000:80"
